FROM apache/airflow:2.9.1

USER root

# Install required system libs
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Install Python libraries needed by your DAGs
RUN pip install --no-cache-dir \
    pymongo \
    apache-airflow-providers-mongo==5.0.0 \
    pandas \
    psycopg2-binary
